#配置访问端口
server:
  port: 10002
  servlet:
    context-path: /
spring:
  application:
    name: goodserver
  datasource:
#引入druid数据源,我的是8.0.15所以driver有所不同5.5的请用com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://176.114.24.87:3306/mymall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
#mybatis
mybatis:
  mapper-locations: classpath:/mybatis/mappers/*.xml
  type-aliases-package: cn.tedu.pojo
  configuration:
    map-underscore-to-camel-case: true
#es
es:
  nodes: 10.42.181.129:9300,10.42.86.124:9300,10.42.118.204:9300