server:
  port: 8104
spring:
  application:
    name: zuulservice2

#zuul路由需要时开启
#zuul:
#  sensitive-headers :
#  routes:
#    api-a:
#      path: /zuul-product/**
#      serviceId: Item-robbin
#    api-b:
#      path: /zuul-pic/**
#      serviceId: Img-robbin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
